### ISSUE TITLE
Bug: SERVER CRASHES

### ISSUE THREAD

**Issue by matesaman9910** [Tau-ri-Dev/Mod-JSG-1.20.x#28]
Sorry I posted this issue in 1.12
Here is the link
https://github.com/Tau-ri-Dev/Mod-JSG-1.12.2/issues/323

**Comment by MineDragonCZ** [comment]
Fixed

**Comment by matesaman9910** [comment]
I don't know if I am doing this wrong but no it isn't fixed
![image](https://github.com/Tau-ri-Dev/Mod-JSG-1.20.x/assets/100013611/712beeab-de67-44c9-a882-5900b5f413ea)
